### PR TITLE
#13 Removing broken client UI

### PR DESCRIPTION
**Pull request by jazeren1**
@sagarsane Removing the client UI.  From what I could tell we just needed to remove the jcr_root directory.  Let me know if I missed something OR if there is something in the jcr_root folder we need to keep.

### CODE REVIEW

**Comment by sagarsane** [comment]
Thanks @jazeren1. Should we also update the `filter.xml` ?

**Comment by jazeren1** [comment]
@sagarsane do we even need a filter xml at all?  I removed both paths that are mentioned here so maybe we can just remove the filter xml for now.

```
<workspaceFilter vesion="1.0">
    <filter root="/apps/grabbit" />
    <filter root="/etc/clientlibs/grabbit" />
</workspaceFilter>
```

**Comment by sagarsane** [comment]
I think we will need to keep `/apps/grabbit` as the install path is `/apps/grabbit/install` ..

**Comment by jazeren1** [comment]
@sagarsane I updated the filter.xml to remove the /etc/ entry.

**Comment by sagarsane** [comment]
Testing looks good :+1:

**Pull request closed without merging**
