### PR TITLE
Fix TravisCI build

### PR DESCRIPTION
**Pull request by jbornemann**
- Builds are passing when they shouldn't.  Probably due to running the Gradle daemon.
- We weren't installing protoc

### CODE REVIEW

**Comment by jbornemann** [comment]
Trying to get the Gradle Daemon to stop spawning.  Travis must be doing something internally.

**Comment by jdigger** [comment]
See #15 ...

**Comment by jbornemann** [comment]
@jdigger @sagarsane take a look if you have the time.  This should solve our build woes.

**Comment by jdigger** [comment]
With the "wrapper wrapper", do we still need to disable the daemon?

**Comment by jdigger** [comment]
I suspect we can remove the disabling the daemon code since the wrapped wrapper should handle exit detection. Otherwise, looks great. Thanks!

**Comment by jbornemann** [comment]
Yeah, I was being paranoid :)  I took it out of the wrapped wrapper.  

Would you prefer the commits to be merged as is, or squashed?

**Comment by sagarsane** [comment]
I see that Travis CI is not happy with the last commit @jbornemann.

**Comment by jbornemann** [comment]
I've seen "com.twcable.grabbit.client.batch.workflows.WorkflowManagerSpec > Should manage multithreading correctly" fail intermittently

**Comment by jbornemann** [comment]
https://github.com/TWCable/grabbit/issues/38

**Comment by sagarsane** [comment]
Okay.

**Comment by sagarsane** [comment]
Changes look good though. +1

**Pull request merged**
