### PR TITLE
 Trying with different travis configs

### LINKED ISSUE #5: Add protocol buffers dependency to travis-ci
Currently, travis-ci does not understand `protoc` compiler and hence cannot build the project. Look into [adding dependencies to travis-ci](http://docs.travis-ci.com/user/installing-dependencies/).

### PR DESCRIPTION
**Pull request by sagarsane**
Working to resolve #5 

@jazeren1 @jdigger

### CODE REVIEW

**Comment by sagarsane** [comment]
@jdigger @jazeren1 looks like the changes are working. `travis-ci` seems to be happier now. Can you please take a look?

Example : https://travis-ci.org/TWCable/grabbit/jobs/53891321

**Comment by sagarsane** [comment]
Well it is a bit flaky. Build # 12 passed but Build # 13 gave "Connection Refused" to `https://repo.adobe.com` again.

**Comment by jazeren1** [comment]
@sagarsane I think there might be something wrong with Travis CI at the moment.  Can't seem to get it to load and looks like our "badge" is off the readme right now. Will try again tomorrow.

travis

**Comment by sagarsane** [comment]
@jazeren1 looks like Travis is back up now.

**Comment by jazeren1** [comment]
:+1:  looks good to me!

**Comment by jdigger** [comment]
...except the build is failing. For some reason `gradlew` is giving an exit code of `0` even though it wasn't successful.

**Comment by sagarsane** [comment]
:-( Yeah that .. and the fact that when it actually passes, it is very unreliable too (i.e., Build # 13.1 passed but # 13.2 and # 13.3 failed. When I get some more time, I will try to play around a bit more.

**Comment by jbornemann** [comment]
Should we close this?

**Comment by jdigger** [comment]
Yeah, in light of #37 resolving the underlying issue.

**Pull request closed without merging**
