### PR TITLE
Add authorization header preemptively

### PR DESCRIPTION
**Pull request by jbornemann**
@sagarsane per #192 

Thought I'd knock it out real quick.

### CODE REVIEW

**Comment by jbornemann** [comment]
@sagarsane thoughts on this? I need to get my hands on AEM again, so I can actually test things my self.

**Comment by sagarsane** [comment]
I haven't had a chance to test this yet .. but the change looks sound to me!

**Comment by pgoodrich** [comment]
@jbornemann We're in the process of testing this now but it will be a while as we check across 6.2 and 6.3 for author and publish

**Comment by pgoodrich** [comment]
@jbornemann @sagarsane Confirmed this is working on 6.2 and 6.3 author and publish.

6.3 has the same pre-requisites as 6.2.  If the Deserialization Firefall is active, it requires the Grabbit-Deserialization-Firewall-Configuration-1.0.zip package and to whitelist the Grabbit bundle until we move away from using the admin session.

**Comment by pgoodrich** [comment]
Confirmed working on 6.1 as well.

**Comment by sagarsane** [comment]
Thanks @pgoodrich !

**Pull request merged**
