### PR TITLE
Initial Commit for Documentation

### PR DESCRIPTION
**Pull request by viveksachdeva**
Changed README file from using Markdown to Asciidoc syntax.. Divided in into separate files under doc directory and they are now referenced from README file...

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/TWCable/grabbit/pull/117" target="_blank">ReviewNinja

**Comment by viveksachdeva** [comment]
@jdigger @sagarsane @jbornemann @jazeren1 : Due to security issues github does allow include directive to render content of the file, so that is rendered as link to the included file...

So I have made changes so table of content directly takes user to the document under docs directory.

Could you please review this..

**Comment by jbornemann** [comment]
@viveksachdeva hate to be a stickler, but it's a bit strange to have every paragraph organized into it's own document. Can't say it flows, or makes information easier to find. It's also formatted a bit strange - both the title, and link below the title are links; and arguably importance of information is out of order.

I'm all for making the documentation pretty, but wondering if we can to structure things a bit different. Maybe something like : 

Front page : 
  - Project purpose
  - Directory 
    - Installing Grabbit: 
      * Links to Releases
      * Version support
    - Using Grabbit:
      * General Layout
      * Running
      * Monitoring 
      * Cleaning
    - Contributing:
      * Prereqs
      * Releasing
    - Library Attributions:
    - License:

Just as an example. This style of doc I think should make it easier to find a category, and snap to a topic. 

Documentation on master has been updated since too, so may want to make sure things are updated. 

Good work so far!

**Comment by viveksachdeva** [comment]
@jbornemann : Agreed that structure should be better.. I have updated this PR.
Changes made:
- Removed autogenerated toc as include directive doesnt work and we ultimately had to specify link to the file under docs
- Restructured some docs
- Added deleteBeforeWrite documentation from master

**Comment by viveksachdeva** [comment]
@jbornemann , @jdigger : Ready for review

**Comment by jdigger** [comment]
The "project purpose" is exactly the kind of thing that really should lead (in-line) in the README.

**Comment by jdigger** [comment]
Under all the links in "Installing Grabbit", there are NO references to the installation files. We really should make it as clear as possible how to actually install the binaries. (Especially since we've seen repeatedly that otherwise most everyone assumes they have to build from source.)

**Comment by jdigger** [comment]
The README's "Using Grabbit / Setup" implies that it will tell you how to set up using Grabbit. However it points to Prerequisites.adoc, which is about how to install `protoc` for development. That will be extremely confusing for people since `protoc` is not required in any way to actually use Grabbit.

**Comment by jdigger** [comment]
The very first item under "Using Grabbit / Running" is "Building from Source", which have nothing to do with running Grabbit.

Anything having to do with building Grabbit (including installing `protoc`) should probably be moved under it's own top-level header of "Grabbit Development".

**Comment by jdigger** [comment]
Let's rename the "Contributing" section to "Grabbit Development" per the prior comment.

**Comment by jdigger** [comment]
There's a lot of changes I'd like to see to the content of the docs, but this is a great start. 😸

**Comment by viveksachdeva** [comment]
@jdigger : Made some changes to this.. 
- "Using grabbit" is now user centric.
- Grabbit development has all information regarding installing binaries and building from source

I am not sure if "building from source" can be clubbed with any other doc as it has only 2-3 lines.

**Comment by jdigger** [comment]
Better.

Think about it from the perspective of someone coming to the project for the first time. What would **_you_** want to see?

"Hm, here's that Grabbit project I was told to check out. What exactly is it? Oh, that sounds useful. How do I install it? Is it a stand-alone program, or a package I install in one of my servers, or...? Where do I get the binaries, or do I need to build from source? Okay, I have it installed -- I think. How do I verify it's installed correctly since I had to put it in multiple places? How do I start a copy job? What about if I'm running Windows? It talks about configuration files, but how do I customize it for my environment? There's a lot of fields in that JSON file that doesn't seem like they're necessary; I wonder if they are and I just don't understand them, in which case I have no idea what I should set them to for my environment. ........"

**Comment by jdigger** [comment]
Vivek, did my comment on the approach to take make sense? Obviously it doesn't all have to happen in this PR, but I would like to see things at least move in that direction.

**Comment by jdigger** [comment]
I like the addition of the samples in a7f6d294d6400f9aa6c71055baf4578711029006. I'm good with squashing and merging this as an intermediate step toward more complete docs.  +1

**Comment by jdigger** [comment]
Squashed and pushed to master.

**Comment by viveksachdeva** [comment]
@jdigger : Yes those made perfect sense to me.. I actually asked a person who did not know about grabbit to go through it and see if it is understandable and started making changes from there...

**Pull request closed without merging**
