### PR TITLE
Update to README for AEM 6.2 SP1 support

### PR DESCRIPTION
**Pull request by jbornemann**
FYI @viveksachdeva

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/TWCable/grabbit/pull/168" target="_blank">ReviewNinja

**Comment by viveksachdeva** [comment]
@jbornemann  : Installing this package did not fix the error for me.. Moreover it has an unmet dependency as I am not using any SP

**Comment by jbornemann** [comment]
@viveksachdeva sorry, I uploaded a new one.

**Comment by jbornemann** [comment]
[Grabbit-Deserialization-Firewall-Configuration-1.0.zip](https://github.com/TWCable/grabbit/files/695261/Grabbit-Deserialization-Firewall-Configuration-1.0.zip)

Any idea how to upload a generic file to https://bintray.com/twcable/aem/Grabbit#files/dependencies? 

Everything I read is about uploading packages

**Comment by jbornemann** [comment]
Nevermind, got it figured out. You have to attach all files to a specific existing package version.

**Comment by sagarsane** [comment]
This is interesting ... getting caught up now.

**Comment by sagarsane** [comment]
Should we have the config be `-amended`? So that we don't overwrite incase the instance Grabbit getting installed to .. already has a config for the Deserialization service?

**Comment by sagarsane** [comment]
I _think_ that way .. we can add only our stuff to the whitelist ... 

Also, I didn't check thoroughly but do we need to update the filter.xml on grabbit so the `/apps/grabbit/config/security` doesn't get inadvertently wiped out when Grabbit is installed / re-installed ?

**Comment by viveksachdeva** [comment]
Agree with both the points from @sagarsane .. ```/apps/grabbit/config/security``` is getting wiped on on grabbit reinstall...

But on installing this package and running a sync from 6.2 -> 6.1 works fine..

**Comment by jbornemann** [comment]
Thanks guys. I didn't even think about filter.xml. I've updated the package, and the PR to accommodate. 

-amended might work if we were dealing with just whitelist, but since blacklist is evaluated first, we have to remove those spring entries.

**Comment by viveksachdeva** [comment]
I am able to do content sync from 6.2 -> 6.1 with this package installed but when I uninstall grabbit, this deserialization config also goes away

**Comment by jbornemann** [comment]
Make sure you have the updated branch installed, and the updated package installed before you test the uninstall. Trying to uninstall when the old branch is already installed won't work.

**Comment by viveksachdeva** [comment]
@jbornemann : Yes I did install the latest package with the updated branch having <exclude pattern="/apps/grabbit/extension(.*)"/>

**Comment by jbornemann** [comment]
Sorry @viveksachdeva, I'm seeing what you are seeing now. Different behavior per install vs uninstall. I forgot how finicky working with the workspace filter is. I've got it down now. Promise :) Mind trying again?

**Comment by viveksachdeva** [comment]
No problem @jbornemann . I will try this one tomorrow..

**Pull request merged**
